// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'Firebase has not been configured for macOS in the Saturn Labs project.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Firebase has not been configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcQsZKnM06cp590D37YVXMl2tptuFvtLM',
    appId: '1:286653865904:web:20552034e78998aba8c075',
    messagingSenderId: '286653865904',
    projectId: 'saturnduospend',
    authDomain: 'saturnduospend.firebaseapp.com',
    storageBucket: 'saturnduospend.firebasestorage.app',
    measurementId: 'G-90PJD9D7WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9sNXleIfUMXZDp1pvLcMtgu-C10V8WYg',
    appId: '1:286653865904:android:df51825d4c949474a8c075',
    messagingSenderId: '286653865904',
    projectId: 'saturnduospend',
    storageBucket: 'saturnduospend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcQsZKnM06cp590D37YVXMl2tptuFvtLM',
    appId: '1:286653865904:ios:69f730766f1e3c3ea8c075',
    messagingSenderId: '286653865904',
    projectId: 'saturnduospend',
    storageBucket: 'saturnduospend.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  // FlutterFire uses a Web Firebase app for Windows. Until a dedicated
  // Windows registration is generated, reuse the registered DuoSpend Web app.
  static const FirebaseOptions windows = web;
}
