import '../../../features/transactions/data/models/product_model.dart';
import 'product_repository.dart';

class ProductSeed {
  static void load(ProductRepository repository) {
    final now = DateTime.now();

    final products = [
      ProductModel(
        id: 'heineken_350ml',
        name: 'Heineken 350ml',
        normalizedName: 'heineken 350ml',
        brand: 'Heineken',
        barcode: '',
        defaultUnit: 'lata',
        productCategoryId: 'drinks',
        productCategoryName: 'Bebidas',
        taxonomyId: 'drinks',
        averagePrice: 0,
        lastPrice: 0,
        lastMerchantId: '',
        favorite: false,
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        id: 'cerveja_350ml',
        name: 'Cerveja 350ml',
        normalizedName: 'cerveja 350ml',
        brand: '',
        barcode: '',
        defaultUnit: 'lata',
        productCategoryId: 'drinks',
        productCategoryName: 'Bebidas',
        taxonomyId: 'drinks',
        averagePrice: 0,
        lastPrice: 0,
        lastMerchantId: '',
        favorite: false,
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        id: 'coca_cola_2l',
        name: 'Coca-Cola 2L',
        normalizedName: 'coca-cola 2l',
        brand: 'Coca-Cola',
        barcode: '',
        defaultUnit: 'un',
        productCategoryId: 'drinks',
        productCategoryName: 'Bebidas',
        taxonomyId: 'drinks',
        averagePrice: 0,
        lastPrice: 0,
        lastMerchantId: '',
        favorite: false,
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        id: 'leite_1l',
        name: 'Leite 1L',
        normalizedName: 'leite 1l',
        brand: '',
        barcode: '',
        defaultUnit: 'L',
        productCategoryId: 'dairy',
        productCategoryName: 'Laticínios',
        taxonomyId: 'dairy',
        averagePrice: 0,
        lastPrice: 0,
        lastMerchantId: '',
        favorite: false,
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        id: 'picanha_kg',
        name: 'Picanha',
        normalizedName: 'picanha',
        brand: '',
        barcode: '',
        defaultUnit: 'kg',
        productCategoryId: 'meat',
        productCategoryName: 'Carnes',
        taxonomyId: 'meat',
        averagePrice: 0,
        lastPrice: 0,
        lastMerchantId: '',
        favorite: false,
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        id: 'arroz_5kg',
        name: 'Arroz 5kg',
        normalizedName: 'arroz 5kg',
        brand: '',
        barcode: '',
        defaultUnit: 'pacote',
        productCategoryId: 'grains',
        productCategoryName: 'Grãos e cereais',
        taxonomyId: 'grains',
        averagePrice: 0,
        lastPrice: 0,
        lastMerchantId: '',
        favorite: false,
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        id: 'acucar_1kg',
        name: 'Açúcar 1kg',
        normalizedName: 'acucar 1kg',
        brand: '',
        barcode: '',
        defaultUnit: 'pacote',
        productCategoryId: 'grains',
        productCategoryName: 'Grãos e cereais',
        taxonomyId: 'grains',
        averagePrice: 0,
        lastPrice: 0,
        lastMerchantId: '',
        favorite: false,
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        id: 'pao_frances',
        name: 'Pão francês',
        normalizedName: 'pao frances',
        brand: '',
        barcode: '',
        defaultUnit: 'kg',
        productCategoryId: 'bakery_products',
        productCategoryName: 'Padaria e massas',
        taxonomyId: 'bakery_products',
        averagePrice: 0,
        lastPrice: 0,
        lastMerchantId: '',
        favorite: false,
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        id: 'detergente_500ml',
        name: 'Detergente 500ml',
        normalizedName: 'detergente 500ml',
        brand: '',
        barcode: '',
        defaultUnit: 'frasco',
        productCategoryId: 'cleaning',
        productCategoryName: 'Limpeza',
        taxonomyId: 'cleaning',
        averagePrice: 0,
        lastPrice: 0,
        lastMerchantId: '',
        favorite: false,
        createdAt: now,
        updatedAt: now,
      ),
      ProductModel(
        id: 'sabao_em_po_1kg',
        name: 'Sabão em pó 1kg',
        normalizedName: 'sabao em po 1kg',
        brand: '',
        barcode: '',
        defaultUnit: 'caixa',
        productCategoryId: 'cleaning',
        productCategoryName: 'Limpeza',
        taxonomyId: 'cleaning',
        averagePrice: 0,
        lastPrice: 0,
        lastMerchantId: '',
        favorite: false,
        createdAt: now,
        updatedAt: now,
      ),
    ];

    for (final product in products) {
      if (!repository.exists(product.name)) {
        repository.save(product);
      }
    }
  }

  ProductSeed._();
}
